[package]
name = "nthu-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["kotatsuyaki <https://blog.kotatsu.dev>"]
license = "MIT"
description = "A template for master theses and doctoral dissertations for NTHU (National Tsing Hua University)."
keywords = ["NTHU", "National Tsing Hua University", "thesis"]
categories = ["thesis"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"